InventarioProyecto/urls.py
from django.contrib import admin
from django.urls import path
from moduloApp.views import * #Todos los elementos de la vista


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index, name='index'),
    path('suma-cantidad/',suma_cantidad, name='suma_cantidad'),
    path('reportes/', reportes, name='reportes'),
    path('generar_reporte_productos/', generar_reporte_productos, name='generar_reporte_productos'),
    path('generar_reporte_sucursales/', generar_reporte_sucursales, name='generar_reporte_sucursales'),
    path('generar_reporte_devoluciones/', generar_reporte_devoluciones, name='generar_reporte_devoluciones'),
    
    path('registrar/', registrar, name= 'registrar'),
    path('cerrarSesion/', cerrarSesion, name= 'cerrarSesion'),
    path('', inicioSesion, name= 'inicioSesion'),

    path('sucursales/', sucursales, name= 'sucursales'),
    path('ingresarSucursales/', ingresarSucursales, name= 'ingresarSucursales'),
    path('editarSucursales/<int:id>', editarSucursales, name= 'editarSucursales'),
    path('borrarSucursales/<int:id>', borrarSucursales, name= 'borrarSucursales'),


    path('productos/', productos, name= 'productos'),
    path('ingresarProductos/', ingresarProductos, name= 'ingresarProductos'),
    path('editarProductos/<int:id>', editarProductos, name= 'editarProductos'),
    path('borrarProductos/<int:id>', borrarProductos, name= 'borrarProductos'),
    path('comprar-producto/<int:producto_id>/', comprar_producto, name='comprarProducto'),
    
    path('historialentrada/', historialentrada, name= 'historialentrada'),


    path('nombreProductos/', nombreProductos, name= 'nombreProductos'),
    path('ingresarNombreProductos/', ingresarNombreProductos, name= 'ingresarNombreProductos'),
    path('editarNombreProductos/<int:id>', editarNombreProductos, name= 'editarNombreProductos'),
    path('borrarNombreProducto/<int:id>', borrarNombreProducto, name= 'borrarNombreProducto'),

    



    path('ingresar_salida_productos/', ingresar_salida_productos, name= 'ingresar_salida_productos'),
    path('salidaProductos/', salidaproductos, name= 'salidaProductos'),
    path('borrarSalida/<int:id>', borrarSalida, name= 'borrarSalida'),
    path('editarSalida/<int:id>', editarSalida, name= 'editarSalida'),


    path('devoluciones/', devoluciones, name= 'devoluciones'),
    path('ingresarDevoluciones/', ingresarDevoluciones, name= 'ingresarDevoluciones'),
    path('borrarDevoluciones/<int:id>', borrarDevoluciones, name= 'borrarDevoluciones'),
    path('editarDevoluciones/<int:id>', editarDevoluciones, name= 'editarDevoluciones'),



    path('viewCategoria/', viewCategoria, name= 'viewCategoria'),
    path('ingresarCategoria/', ingresarCategoria, name= 'ingresarCategoria'),
    path('borrarCategoria/<int:id>', borrarCategoria, name= 'borrarCategoria'),
    path('editarCategoria/<int:id>', editarCategoria, name= 'editarCategoria'),


    path('editarDevoluciones/<int:id>/<int:cantidad>/', editarDevoluciones, name='editarDevoluciones'),

    path('generar-reporte/', generar_reporte, name='generar_reporte'),
    path('generar-reporte2/', generar_reporte2, name='generar_reporte2'),

    path('perfil/', perfil, name='perfil'),
    path('editar_perfil/', editar_perfil, name='editar_perfil'),


    path('usuarios/', usuarios, name='usuarios'),
    path('borrarUsuario/<int:id>/', borrarUsuario, name='borrarUsuario'),
    path('get_nombre_producto/', get_nombre_producto, name='get_nombre_producto'),
    path('get_id_producto/', get_id_producto, name='get_id_producto'),


    




]

moduloApp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *

class ingresarProductosForm(forms.Form):
    nombre = forms.ModelChoiceField(queryset=nombreProducto.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    id_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipo_producto = forms.ModelChoiceField(queryset=categoria.objects.all(), label="Categoría de Producto", widget=forms.Select(attrs={'class': 'form-control'}))
    valor_unitario = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    sucursal = forms.ModelChoiceField(queryset=sucursal.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    fecha = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), initial=timezone.now().date())
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}))


class ingresarProductosModelForm(forms.ModelForm):
    class Meta:
        model = producto
        fields = '__all__'
    nombre = forms.ModelChoiceField(queryset=nombreProducto.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    id_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipo_producto = forms.ModelChoiceField(queryset=categoria.objects.all(), label="Categoría de Producto", widget=forms.Select(attrs={'class': 'form-control'}))
    valor_unitario = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    sucursal = forms.ModelChoiceField(queryset=sucursal.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    fecha = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), initial=timezone.now().date())
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}))




class ingresarSalidaProductosForm(forms.Form):
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    id_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipo_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    fecha = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), initial=timezone.now().date())
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}))

class ingresarSalidaProductosModelForm(forms.ModelForm):
    class Meta:
        model = ingresarSalidaProductos
        fields = '__all__'
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    id_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipo_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    fecha = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), initial=timezone.now().date())
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}))

class ingresarEntradaProductosForm(forms.Form):
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipo_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    fecha = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), initial=timezone.now().date())
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}))

class ingresarEntradaProductosModelForm(forms.ModelForm):
    class Meta:
        model = ingresarSalidaProductos
        fields = '__all__'
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    tipo_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    fecha = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), initial=timezone.now().date())
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}))





class ingresarDevolucionesForm(forms.Form):
    id_venta = forms.ModelChoiceField(queryset=ingresarSalidaProductos.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    fecha = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), initial=timezone.now().date())
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}))


class ingresarDevolucionesModelForm(forms.ModelForm):
    class Meta:
        model = devolucion
        exclude = ['nombre_producto','id_producto'] 
        fields = '__all__'
    id_venta = forms.ModelChoiceField(queryset=ingresarSalidaProductos.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    fecha = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), initial=timezone.now().date())
    hora = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control', 'type': 'time'}))

class ingresarSucursalesForm(forms.Form):
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    id_sucursal = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    direccion = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    numero_telefono = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))

class ingresarSucursalesModelForm(forms.ModelForm):
    class Meta:
        model = sucursal
        fields = '__all__'
    nombre = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    id_sucursal = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    direccion = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    numero_telefono = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))

class stockForm(forms.Form):
    id_producto_stock = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    nombre_producto = forms.ModelChoiceField(queryset=producto.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    tipo_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))

class stockModelForm(forms.ModelForm):
    class Meta:
        model = stock
        fields = '__all__'
    id_producto_stock = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    nombre_producto = forms.ModelChoiceField(queryset=producto.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    tipo_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))

class nombreProductoForm(forms.Form):
    nombre_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    id_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

class nombreProductoModelForm(forms.ModelForm):
    class Meta:
        model = nombreProducto
        fields = '__all__'
        
    nombre_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    id_producto = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

class CustomUserCreationForm(UserCreationForm):
    rol = forms.ChoiceField(choices=Rol.ROLES_CHOICES, required=True)

    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('rol','username', 'first_name', 'last_name','password1','password2')





class categoriaForm(forms.Form):
    nombre_categoria = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    id_categoria = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

class categoriaModelForm(forms.ModelForm):
    class Meta:
        model = categoria
        fields = '__all__'
        
    nombre_categoria = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    id_categoria = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

templates/devoluciones/devoluciones.html
{% extends "sistema/base.html" %}

{% block title %}
Devoluciones
{% endblock %}

{% block contenido %}
  <h1>Historial de Devoluciones</h1>

  {% if devoluciones %}
    <div class="container text-center">
      <div class="table-responsive bg-light mb-3">
        <table id="example" class="table table-bordered table-striped" style="width:100%">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">ID venta</th>
              <th scope="col">Nombre del producto</th>
              <th scope="col">ID producto</th> <!-- Agregar columna ID producto -->
              <th scope="col">Cantidad</th>
              <th scope="col">Fecha</th>
              <th scope="col">Hora</th>
              <th scope="col">
                {% if user.is_authenticated and user.rol.rol != 'US' %} 
                 Acción
                {% endif %}
              </th>
            </tr>
          </thead>
          <tbody>
            {% for devolucion in devoluciones %}
              <tr>
                <td scope="row">{{ devolucion.id }}</td>
                <td scope="row">{{ devolucion.id_venta_id }}</td>
                <td scope="row">{{ devolucion.nombre_producto }}</td>
                <td scope="row"><span id="id_producto">{{ devolucion.id_producto }}</span></td>
                <td scope="row">{{ devolucion.cantidad }}</td>
                <td scope="row">{{ devolucion.fecha }}</td>
                <td scope="row">{{ devolucion.hora }}</td>
                <td>
                  {% if user.is_authenticated and user.rol.rol != 'US' %}
                  <div class="row">
                    <div class="col-3 m-2">
                      <a href="{% url 'editarDevoluciones' id=devolucion.id cantidad=devolucion.cantidad %}" class="btn btn-warning">Editar</a>
                    </div>
                    <div class="col-3 m-2">
                      <button href="#" id="confirmacionBorradoModal{{ devolucion.id }}" class="btn btn-danger" data-toggle="modal" data-target="#confirmacionBorradoModal{{ devolucion.id }}">Borrar</button>
                    </div>
                  </div>
                  {% endif %}
                </td>
              </tr>

              <!-- alerta de confirmacion -->
              <script>
                $(document).ready(function() {
                  $('#confirmacionBorradoModal{{ devolucion.id }}').click(function() {
                    const swalWithBootstrapButtons = Swal.mixin({
                      customClass: {
                        confirmButton: 'btn btn-success',
                        cancelButton: 'btn btn-danger'
                      },
                      buttonsStyling: false
                    });
                    swalWithBootstrapButtons.fire({
                      title: '¿Estás seguro de que deseas eliminar esta devolución?',
                      text: "¡No podrás revertir esto!",
                      icon: 'warning',
                      showCancelButton: true,
                      confirmButtonText: 'Sí, borrar',
                      cancelButtonText: 'No, cancelar',
                      reverseButtons: true,
                      allowOutsideClick: false,
                    }).then((result) => {
                      if (result.isConfirmed) {
                        // Realizar la acción de borrado
                        swalWithBootstrapButtons.fire({
                          title: 'Deleted',
                          text: 'La devolución fue eliminada con éxito :)',
                          icon: 'success',
                          showConfirmButton: true,
                          allowOutsideClick: false,
                        }).then(() => {
                          // Redireccionar a la URL después de mostrar el mensaje y esperar 1 segundo
                          setTimeout(function() {
                            window.location.href = "{% url 'borrarDevoluciones' id=devolucion.id %}";
                          });
                        });
                      } else if (result.dismiss === Swal.DismissReason.cancel) {
                        swalWithBootstrapButtons.fire({
                          title: 'Cancelado',
                          text: 'La devolución no fue eliminada :)',
                          icon: 'error',
                          showCancelButton: false, // Ocultar el botón de cancelar
                          showCloseButton: true, // Mostrar el botón "Cerrar"
                        }).then(() => {
                          // Redireccionar a la URL después de que se muestre el mensaje
                          window.location.href = "{% url 'devoluciones' %}";
                        });
                      }
                    });
                  });
                });
              </script>

            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <script>
      $(document).ready(function() {
        $('#id_id_venta').change(function() {
          var id_venta = $(this).val();
          $.ajax({
            type: 'GET',
            url: '/get_nombre_producto/',
            data: {
              'id': id_venta
            },
            dataType: 'json',
            success: function(data) {
              $('#id_id_producto').val(data.id_producto);
              $('#id_producto').text(data.id_producto); // Actualiza el contenido del span con el ID del producto
              $('#id_nombre_producto').text(data.nombre_producto);
            },
            error: function(xhr, textStatus, errorThrown) {
              console.log('Error:', errorThrown);
            }
          });
        });
      });
    </script>
    
    
  {% else %}
    <p>No hay devolucion ingresadas.</p>
  {% endif %}
  <a href="{% url 'ingresarDevoluciones' %}" class="btn btn-primary">Ingresar Devoluciones</a>
{% endblock %}

templates/devoluciones/ingresarDevoluciones.html
{% extends "sistema/base.html" %}

{% block title %}
Ingreso de devoluciones
{% endblock title %}

{% block contenido %}



<div class="container card mt-5">
    {{ error }}
    
    <form method="POST" class="my-3">
        <h1 class="text-center display-3 mb-5">Ingresar Devolucion</h1>
        {% csrf_token %}

        {{ form.as_p }}

        <a href="{% url 'devoluciones' %}" class="btn btn-dark">
            Volver
        </a>
        <button class="btn btn-primary float-right">
            Ingresar
        </button>

    </form>
</div>

{% endblock %}